### ISSUE TITLE
bug: Unexpected keyword argument 'reasoning_effort'

### ISSUE THREAD

**Issue by rubin55** [mistralai/mistral-vibe#549]
### Component

CLI

### Summary

I'm trying to use `vibe`. I immediately get the following after doing a "Hello, Vibe!" test-prompt:

```
Error: API error from mistral (model: mistral-vibe-cli-latest): Chat.stream_async() got an unexpected keyword argument 'reasoning_effort'
```

### Reproduction steps

I installed `vibe` 2.7.0, and started the command, clean session, installed mij vibe key and prompted.

### Versions / environment

vibe 2.7.0, Arch Linux

### Logs & screenshots
<img width="1624" height="564" alt="Image" src="https://github.com/user-attachments/assets/20021b03-1b76-4e02-8d10-35dbd4069f9f" />

**Comment by rubin55** [comment]
I figured it out. This was due to [python-mistralai](https://aur.archlinux.org/packages/python-mistralai) being out of date; After updating to 2.2.0, `vibe` works again.
