### ISSUE TITLE
bug: crash on launch with vibe 2.7.5

### ISSUE THREAD

**Issue by loledeck** [mistralai/mistral-vibe#595]
### Component

CLI

### Summary

Since I upgraded to 2.7.5, vibe crashes on launch with the message:
`ImportError: cannot import name 'deep_update' from 'pydantic_settings.sources.base' (/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/pydantic_settings/sources/base.py)`

This is on macOS 26.3.1, python 3.12.10

Full callstack:

```
Traceback (most recent call last):
  File "/Users/johndoe/.pyenv/versions/3.12.10/bin/vibe", line 3, in <module>
    from vibe.cli.entrypoint import main
  File "/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/vibe/cli/entrypoint.py", line 11, in <module>
    from vibe.core.agents.models import BuiltinAgentName
  File "/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/vibe/core/agents/__init__.py", line 3, in <module>
    from vibe.core.agents.manager import AgentManager
  File "/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/vibe/core/agents/manager.py", line 13, in <module>
    from vibe.core.config.harness_files import get_harness_files_manager
  File "/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/vibe/core/config/__init__.py", line 3, in <module>
    from vibe.core.config._settings import (
  File "/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/vibe/core/config/_settings.py", line 26, in <module>
    from pydantic_settings.sources.base import deep_update
ImportError: cannot import name 'deep_update' from 'pydantic_settings.sources.base' (/Users/johndoe/.pyenv/versions/3.12.10/lib/python3.12/site-packages/pydantic_settings/sources/base.py)
```

### Reproduction steps

Upgrade to the latest public version:
`pip install --upgrade mistral-vibe`

Then:
`vibe`

### Versions / environment

mistral-vibe 2.7.5, pip 26.0.1, macOS 26.3.1

### Logs & screenshots

```shell

```

**Comment by loledeck** [comment]
Fixed by manually updating pydantic-settings:
pip install --upgrade pydantic-settings
